import 'package:flutter/material.dart';

class Constants {
  static final appBlack = Color(0xff171A20);
  static final appGrey = Color(0xff2a3038);
  static final appLightGrey = Color(0xff606576);
  static final appBlue = Color(0xff0075F7);
  static double h = 0;
  static double w = 0;
}

List<String> interestList = [
  "Photography",
  "Gaming",
  "Coding",
  "Playing",
  "Football",
  "Swimming",
  "Cooking",
  "Music",
  "Reading",
  "Traveling",
  "Art",
  "Science",
  "Dancing",
  "Hiking",
  "Yoga",
  "Movies",
  "Sports",
  "Writing",
  "Fishing",
  "Shopping",
];

var items = [
  "English",
  "Spanish",
  "Mandarin Chinese",
  "Hindi",
  "Arabic",
  "Bengali",
  "Portuguese",
  "Russian",
  "Urdu",
  "Indonesian",
  "French",
  "German",
  "Japanese",
  "Swahili",
  "Turkish",
  "Vietnamese",
  "Korean",
  "Italian",
  "Tamil",
  "Telugu",
  "Marathi",
  "Thai",
  "Dutch",
  "Yoruba",
  "Filipino",
  "Polish",
  "Ukrainian",
  "Malayalam",
  "Kannada",
  "Gujarati",
  "Javanese",
  "Sindhi",
  "Farsi (Persian)",
  "Pashto",
  "Kurdish",
  "Amharic",
  "Oromo",
  "Igbo",
  "Zulu",
  "Afrikaans",
  "Hausa",
  "Serbo-Croatian",
  "Czech",
  "Slovak",
  "Bulgarian",
  "Hungarian",
  "Finnish",
  "Swedish",
  "Norwegian",
  "Danish",
  "Greek",
  "Hebrew",
  "Romanian",
  "Burmese",
  "Khmer",
  "Malay",
  "Lao",
  "Nepali",
  "Bhojpuri",
  "Maithili",
  "Sundanese",
  "Uzbek",
  "Kazakh",
  "Tatar",
  "Kurdish",
  "Komi",
  "Georgian",
  "Armenian",
  "Azerbaijani",
  "Tigrinya",
  "Somali",
  "Nigerian Pidgin",
  "Fijian",
  "Hawaiian",
  "Samoan",
  "Tongan",
  "Maori",
  "Cherokee",
  "Navajo",
  "Inuktitut",
  "Greenlandic",
  "Haitian Creole",
  "Luxembourgish",
  "Esperanto",
  "Klingon", // Just for fun!
];
