// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAe-HatW8A6sydm6R_1yrY713JCfZ6tZMs',
    appId: '1:60930318154:web:92e0745215d72f071a2bb3',
    messagingSenderId: '60930318154',
    projectId: 'nightlifydatingapp',
    authDomain: 'nightlifydatingapp.firebaseapp.com',
    storageBucket: 'nightlifydatingapp.appspot.com',
    measurementId: 'G-KSE97MNVE5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBb2JvYmDMHJibwdSQnzIzNTAGS6850saA',
    appId: '1:60930318154:android:81c4a5313bc17f8c1a2bb3',
    messagingSenderId: '60930318154',
    projectId: 'nightlifydatingapp',
    storageBucket: 'nightlifydatingapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8fOiva8TIL_zwlqdnnqaxUcrRnl2lIoc',
    appId: '1:60930318154:ios:4017d2f7b31613cb1a2bb3',
    messagingSenderId: '60930318154',
    projectId: 'nightlifydatingapp',
    storageBucket: 'nightlifydatingapp.appspot.com',
    androidClientId: '60930318154-1m58q786jet9020d5ga8h99gmt6jc5ui.apps.googleusercontent.com',
    iosClientId: '60930318154-c6t6opsqj3e8pcal13gnp8lcqg53qbn4.apps.googleusercontent.com',
    iosBundleId: 'com.example.nightlify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8fOiva8TIL_zwlqdnnqaxUcrRnl2lIoc',
    appId: '1:60930318154:ios:9b0e48984e28d8371a2bb3',
    messagingSenderId: '60930318154',
    projectId: 'nightlifydatingapp',
    storageBucket: 'nightlifydatingapp.appspot.com',
    androidClientId: '60930318154-1m58q786jet9020d5ga8h99gmt6jc5ui.apps.googleusercontent.com',
    iosClientId: '60930318154-842u427e81e4hdm16tf8g07fska5nmrk.apps.googleusercontent.com',
    iosBundleId: 'com.example.nightlify.RunnerTests',
  );
}
